### ISSUE TITLE
Package not in Herd?

### ISSUE THREAD

**Issue by russel** [renatoathaydes/specks#1]
This package has not been worked on for a while, is it still intended for use? Currently, there is no package for this in Herd.

**Comment by renatoathaydes** [comment]
I was waiting for Ceylon 1.2 to get back to working on this. There were too many issues I could not solve properly with 1.1.

I am hoping to make it work much more nicely with 1.2 features.

But why it's not in Herd, I don't know... will ask the Ceylon team.

**Comment by russel** [comment]
I am fairly over-worked until 2016, but if there is anything I can do to help progress things once 2015 has gone, let me know.

**Comment by renatoathaydes** [comment]
ok, cool!

**Comment by renatoathaydes** [comment]
Finished the redesign, merged to master.
Now just waiting for Ceylon Herd to approve my request to publish!

**Comment by renatoathaydes** [comment]
Published version 0.2.0 to Herd just now! Hope you like the new design.
