### ISSUE TITLE
JavaScript `errorCheck` Block not usable 

### ISSUE THREAD

**Issue by dlkw** [renatoathaydes/specks#15]
Using the following Specification on the JS runtime
```ceylon
    test
    shared Specification strange() => Specification {
        errorCheck {
            function when() => 1/0;
            expectToThrow(`Exception`)
        }
    };
```
gives the error message
```
ceylon.language::AssertionError "Assertion failed: If you do not provide any examples, your 'when' function must not take any parameters.
	violated is Callable<Anything,[]> when"
```

**Comment by renatoathaydes** [comment]
I tried the implementation code in the Web IDE and it seems it works fine there, but if I use the specks package, the same code fails.... I would think this is due to a bug in the CeylonJS compiler when my JS module was built, which has been fixed more recently.

Can you please build Specks with the latest compiler for JS and confirm that it now works?

**Comment by dlkw** [comment]
I'm using the IDE (Eclipse) for doing work with Ceylon, so I'm using Ceylon 1.3.3. I added the freshly built specks module as a dependency to my project (the `message` parameter with the `noCheck` default value from my pull request https://github.com/renatoathaydes/specks/pull/17 is visible there).

Running the test with this configuration still fails. Do you mean a newer version of Ceylon than 1.3.3? I could not find out how to get that into Eclipse. I'll try using the command line (with which I'm unfamiliar), but that has to wait until the week-end.

**Comment by dlkw** [comment]
I tried the following with Ceylon 1.3.3. On JVM it runs ok, but on JS, it behaves like in the comments.
```ceylon

shared void run()
{
    void rrr<Where=[]>(Callable<Anything, Where> when)
    {
        assert (is Callable<Anything, []> when);
    }
    print(1);
    rrr(()=>1/0); // passes assertion on JVM and JS
    print(2);
    rrr{when()=>1/0;}; // fails assertion on JS (passes on JVM)
    print(3);
}
```
Did not test (yet, see above) with an unreleased newer Ceylon version.

**Comment by renatoathaydes** [comment]
IF your last message is correct, then it confirms the bug is in the CeylonJS  compiler. Please create an issue in their tracker: https://github.com/eclipse/ceylon/tree/master/compiler-js
